development:
  adapter: postgresql
  encoding: unicode
  database: moavia_development
  host: localhost
  pool: 5
  username: postgres
  password: postgres

production:
  adapter: postgresql
  encoding: unicode
  database: moavia_production
  host: localhost
  pool: 5
  username: postgres
  password: postgres


test:
  adapter: postgresql
  encoding: unicode
  database: moavia_test
  host: localhost
  pool: 5
  username: postgres
  password: postgres